learning_templates/basic_app/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li> <a class="navbar-brand" href="{% url "index" %}">Brand</a> </li>
                    <li> <a class="navbar-link" href="{% url "admin:index" %}">Admin</a> </li>
                    <li> <a class="navbar-link" href="{% url "basic_app:other" %}">Other</a> </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}

            {% endblock %}
        </div>
    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
{% block body_block %}
        <h1>Welcome to Index!!</h1>
        <h1>{{ text|cutstrip:'world' }}</h1>
        <h1>{{ number|add:"99" }}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}\
{% block body_block %}
        <h1>Welcome to Other!!</h1>
        <h2>This is example of Template Inheritence</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Relative_urls</title>
    </head>
    <body>
        <h1>Welcome to Relative Urls Templates</h1>
        <a href="{% url "basic_app:other" %}">The Other Page</a>
        <a href="{% url "admin:index" %}">Admin Page</a>
        <a href="{% url "index" %}">Index</a>
    </body>
</html>